import type { Action } from "./types";
import { danceActions } from "./danceData";
const a = (
  name: string,
  duration: number,
  keyframes: Action["keyframes"],
  categories = ["Fight"],
  participants: ("actor" | "prop")[] = ["actor"],
): Action => ({
  id: name.toLowerCase().replaceAll(" ", "_"),
  name,
  duration,
  keyframes,
  categories,
  tags: [...categories, name.toLowerCase()],
  participants,
});
const pose = (
  name: string,
  end: string = "neutral_stand",
  categories = ["Lifestyle"],
  participants: ("actor" | "prop")[] = ["actor"],
): Action =>
  a(
    name,
    0.7,
    [
      { time: 0, pose: "neutral_stand", easing: "ease-in-out" },
      { time: 0.7, pose: end, easing: "linear" },
    ],
    categories,
    participants,
  );
const travel = (
  name: string,
  dx: number,
  duration: number,
  categories = ["Movement"],
): Action =>
  a(
    name,
    duration,
    [
      { time: 0, pose: "step_forward_start", easing: "ease-in-out" },
      { time: duration, pose: "step_forward_contact", easing: "linear", dx },
    ],
    categories,
  );
export const actions: Action[] = [
  a(
    "Idle",
    0.6,
    [
      { time: 0, pose: "idle", easing: "ease-in-out" },
      { time: 0.6, pose: "idle", easing: "linear" },
    ],
    ["Lifestyle", "Fight"],
  ),
  a("Fight Stance", 0.35, [
    { time: 0, pose: "Fight Stance", easing: "ease-out" },
    { time: 0.35, pose: "Fight Stance", easing: "linear" },
  ]),
  travel("Step Forward", 80, 0.45, ["Movement", "Fight"]),
  travel("Step Back", -80, 0.45, ["Movement", "Fight"]),
  travel("Walk", 180, 1.2, ["Lifestyle", "Movement"]),
  travel("Walk Slowly", 130, 1.8, ["Lifestyle", "Movement"]),
  travel("Walk Fast", 250, 0.85, ["Lifestyle", "Movement"]),
  travel("Run", 330, 0.7, ["Movement", "Cinematic Action"]),
  travel("Approach", 150, 1.1, ["Social", "Romance", "Family"]),
  travel("Step Away", -120, 0.8, ["Social", "Romance"]),
  a("Dash Forward", 0.35, [
    { time: 0, pose: "Fight Stance", easing: "snap" },
    { time: 0.35, pose: "Fight Stance", easing: "ease-out", dx: 180 },
  ]),
  a("Straight Punch", 0.55, [
    { time: 0, pose: "Fight Stance", easing: "ease-in" },
    { time: 0.22, pose: "Punch Anticipation", easing: "snap" },
    { time: 0.34, pose: "Punch Extension", easing: "hold" },
    { time: 0.55, pose: "Fight Stance", easing: "linear" },
  ]),
  a("Hook", 0.6, [
    { time: 0, pose: "Punch Anticipation", easing: "snap" },
    { time: 0.3, pose: "Punch Extension", easing: "ease-out" },
    { time: 0.6, pose: "Fight Stance", easing: "linear" },
  ]),
  a("Uppercut", 0.6, [
    { time: 0, pose: "Crouch", easing: "snap" },
    { time: 0.3, pose: "Punch Extension", easing: "ease-out" },
    { time: 0.6, pose: "Fight Stance", easing: "linear" },
  ]),
  a("Low Kick", 0.65, [
    { time: 0, pose: "Kick Anticipation", easing: "snap" },
    { time: 0.35, pose: "Kick Extension", easing: "hold" },
    { time: 0.65, pose: "Fight Stance", easing: "linear" },
  ]),
  a("High Kick", 0.75, [
    { time: 0, pose: "Kick Anticipation", easing: "snap" },
    { time: 0.4, pose: "Kick Extension", easing: "hold" },
    { time: 0.75, pose: "Fight Stance", easing: "linear" },
  ]),
  a(
    "Jump",
    0.8,
    [
      { time: 0, pose: "Jump Anticipation", easing: "snap" },
      { time: 0.35, pose: "idle", easing: "ease-out", dy: -220 },
      { time: 0.8, pose: "Fight Stance", easing: "linear" },
    ],
    ["Movement", "Cinematic Action", "Fight"],
  ),
  pose("Sit Down", "crouch", ["Lifestyle", "Family", "Prop Interaction"]),
  pose("Sit", "ground_down_back", ["Lifestyle", "Family", "Prop Interaction"]),
  pose("Stand Up", "stand_recovery", ["Lifestyle"]),
  pose("Relaxed Stand", "idle_relaxed", ["Lifestyle"]),
  pose("Wave", "high_guard", ["Lifestyle", "Social", "Family"]),
  pose("Point", "straight_punch_extension", ["Lifestyle", "Social"]),
  pose("Think", "cover_head", ["Lifestyle", "Reactions"]),
  pose("Check Phone", "guard_body", ["Lifestyle", "Prop Interaction"]),
  pose("Drink", "uppercut_anticipation", ["Lifestyle", "Prop Interaction"]),
  pose("Read", "guard_body", ["Lifestyle", "Prop Interaction"]),
  pose("Handshake", "straight_punch_extension", ["Social"], ["actor", "actor"]),
  pose("High Five", "high_guard", ["Social", "Family"], ["actor", "actor"]),
  pose(
    "Hug",
    "guard_body",
    ["Social", "Romance", "Family"],
    ["actor", "actor"],
  ),
  pose(
    "Hold Hands",
    "straight_punch_extension",
    ["Romance", "Family"],
    ["actor", "actor"],
  ),
  pose("Kiss", "lean_back", ["Romance"], ["actor", "actor"]),
  pose(
    "Give Flower",
    "straight_punch_extension",
    ["Romance", "Prop Interaction"],
    ["actor", "actor", "prop"],
  ),
  pose(
    "Group Hug",
    "guard_body",
    ["Family", "Social"],
    ["actor", "actor", "actor"],
  ),
  pose(
    "Family Photo Pose",
    "neutral_stand",
    ["Family"],
    ["actor", "actor", "actor"],
  ),
  pose("Basic Groove", "fight_guard", ["Dance"]),
  pose("Step Left", "sidestep_left", ["Dance"]),
  pose("Step Right", "sidestep_right", ["Dance"]),
  pose("Spin", "spin_end", ["Dance", "Cinematic Action"]),
  pose("Partner Hold", "guard_body", ["Dance", "Romance"]),
  pose("Slow Dance", "bow_stance", ["Dance", "Romance"]),
  pose("Sword Ready", "sword_neutral", ["Sword / Melee"]),
  pose("Raise Sword", "sword_ready_overhead", ["Sword / Melee"]),
  a("Swing Horizontal",1,[{time:0,pose:"sword_ready_side",easing:"ease-in"},{time:.42,pose:"sword_slash_horizontal_contact",easing:"snap"},{time:.62,pose:"sword_slash_horizontal_follow",easing:"ease-out"},{time:1,pose:"sword_recovery",easing:"ease-in-out"}],["Sword / Melee"]),
  a("Swing Diagonal",.95,[{time:0,pose:"sword_guard_high",easing:"ease-in"},{time:.4,pose:"sword_slash_diagonal_contact",easing:"snap"},{time:.6,pose:"sword_slash_horizontal_follow",easing:"ease-out"},{time:.95,pose:"sword_recovery",easing:"ease-in-out"}],["Sword / Melee"]),
  a("Sword Thrust",.9,[{time:0,pose:"sword_thrust_anticipation",easing:"ease-in"},{time:.4,pose:"sword_thrust_contact",easing:"snap"},{time:.9,pose:"sword_guard_mid",easing:"ease-out"}],["Sword / Melee"]),
  pose("Weapon Block", "sword_clash", ["Sword / Melee"]),
  pose("Weapon Clash Pose", "sword_clash", ["Sword / Melee"]),
  pose("Surprised", "high_guard", ["Reactions"]),
  pose("Happy", "high_guard", ["Reactions"]),
  pose("Sad", "idle_relaxed", ["Reactions"]),
  pose("Scared", "cover_head", ["Reactions"]),
  pose("Facepalm", "cover_head", ["Reactions"]),
  pose("Pick Up", "crouch", ["Prop Interaction"]),
  pose("Put Down", "crouch", ["Prop Interaction"]),
  pose("Hold", "guard_body", ["Prop Interaction"]),
  pose("Give", "straight_punch_extension", ["Prop Interaction"]),
  pose("Catch", "high_guard", ["Prop Interaction"]),
  ...danceActions,
];
