import { basePose } from "./animation";
import type { Action, JointName, Pose } from "./types";

export const danceStyles: Record<string, string[]> = {
  "Basic / Freestyle": [
    "Freestyle Neutral",
    "Open Groove",
    "Closed Groove",
    "Side Reach",
    "Cross Step",
    "Bounce Low",
  ],
  Techno: [
    "Techno Neutral",
    "Wide Techno Stance",
    "Hands Up",
    "One Hand Up",
    "Double Hand Raise",
    "Side Reach Pulse",
    "Forward Pulse",
    "Body Lean Left",
    "Body Lean Right",
    "Head Down Groove",
    "Shoulder Pulse",
    "Elbow Pump",
    "Arm Pump",
    "Bounce High",
    "Techno Freeze",
  ],
  "Robot / Popping": [
    "Robot Neutral",
    "Angular Guard",
    "Elbow Lock Left",
    "Elbow Lock Right",
    "Double Elbow Lock",
    "Wrist Angle",
    "Mechanical Reach",
    "Mechanical Point",
    "Chest Forward",
    "Chest Back",
    "Head Tilt",
    "Mechanical Lean",
    "90 Degree Arms",
    "Box Arms",
    "Freeze Left",
    "Freeze Right",
    "Low Robot Pose",
    "High Robot Pose",
  ],
  Breakdance: [
    "Toprock Neutral",
    "Toprock Step",
    "Toprock Cross",
    "Drop Preparation",
    "Low Crouch",
    "Floor Entry",
    "Hand Support",
    "Two Hand Support",
    "One Hand Balance",
    "Baby Freeze",
    "Chair Freeze",
    "Side Freeze",
    "Turtle Freeze",
    "Headstand Preparation",
    "Headstand",
    "Handstand",
    "One Hand Freeze",
    "Leg Split Freeze",
    "Kick Out",
    "Floor Sweep",
    "Power Move Preparation",
    "Power Move Extension",
  ],
  "Hip-Hop": [
    "Hip-Hop Neutral",
    "Wide Groove",
    "Low Groove",
    "Lean Left",
    "Lean Right",
    "Shoulder Drop",
    "Cross Arms",
    "Open Arms",
    "Low Point",
    "One Hand Up Groove",
    "Double Hands Up Groove",
    "Step Pose",
    "Cross Step Groove",
    "Kick Step",
    "Bounce Down",
    "Bounce Up",
    "Turn Pose Groove",
    "Hip-Hop Freeze",
  ],
  Shuffle: [
    "Running Man Start",
    "Running Man Contact",
    "Running Man Passing",
    "Running Man Extension",
    "T-Step Left",
    "T-Step Right",
    "Heel Up",
    "Toe Contact",
    "Shuffle Kick",
    "Shuffle Slide",
    "Shuffle Cross Step",
    "Shuffle Turn",
  ],
  "Disco / Retro": [
    "Disco Point Up",
    "Disco Point Side",
    "Disco Double Point",
    "Hip Shift",
    "Retro Side Step",
    "Retro Wide Step",
    "Arm Sweep",
    "Shoulder Groove",
    "Retro Turn",
    "Partner Groove",
    "Celebration Pose",
  ],
  Ballet: [
    "Neutral Ballet Stand",
    "First Position",
    "Second Position",
    "Arabesque Pose",
    "Attitude Pose",
    "Ballet One Leg Balance",
    "High Leg Extension",
    "Side Leg Extension",
    "Front Leg Extension",
    "Arms First",
    "Arms Open",
    "Arms Overhead",
    "Deep Bend",
    "Ballet Lunge",
    "Kneeling Ballet Pose",
    "Floor Extension",
    "Split Pose",
    "Leap Preparation",
    "Leap Extension",
    "Ballet Landing Pose",
    "Turn Preparation",
    "Turn Pose",
    "Elegant Reach",
    "Back Arch",
    "Side Bend",
  ],
  Contemporary: [
    "Contemporary Deep Bend",
    "Contemporary Back Arch",
    "Side Arch",
    "Floor Reach",
    "One Hand Floor",
    "Two Hands Floor",
    "Crab Support",
    "Kneeling Reach",
    "Contemporary Wide Squat",
    "Contemporary Low Squat",
    "Asymmetric Balance",
    "Extreme Side Reach",
    "Twisted Torso",
    "Contemporary Floor Split",
    "Floor Sit",
    "Extended Floor Pose",
    "Jump Reach",
    "Falling Shape",
    "Recovery Shape",
    "Curved Body",
    "Open Body",
    "Closed Body",
  ],
  Jazz: [
    "Jazz Neutral",
    "Jazz Hands",
    "Jazz Lunge",
    "Jazz Kick",
    "Jazz Turn",
    "Jazz Leap",
  ],
  "Swing / Lindy": [
    "Swing Neutral",
    "Swing Step",
    "Lindy Kick",
    "Partner Open",
    "Partner Closed",
    "Swing Finish",
  ],
  "Partner Dance": [
    "Partner Approach",
    "Take Hands",
    "Partner Hold",
    "Side Step Together",
    "Open Position",
    "Closed Position",
    "Underarm Turn",
    "Partner Dip",
    "Partner Release",
    "Partner End Pose",
  ],
  "Slow Dance": [
    "Slow Dance Hold",
    "Slow Sway Left",
    "Slow Sway Right",
    "Lean Closer",
    "Slow Turn",
    "Slow Dance End",
  ],
  "Latin-inspired": [
    "Latin Neutral",
    "Hip Accent Left",
    "Hip Accent Right",
    "Latin Step",
    "Latin Turn",
    "Latin Finish",
  ],
  "Celebration / Party": [
    "Party Hands Up",
    "Party Jump",
    "Party Point",
    "Party Bounce",
    "Victory Freeze",
    "Group Celebration",
  ],
  "Acrobatic Dance": [
    "Dance Cartwheel",
    "Dance Handstand",
    "Aerial Split",
    "Acrobatic Leap",
    "Power Spin Pose",
    "Acrobatic Landing",
  ],
};

const slug = (value: string) =>
  `dance_${value
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")}`;
const point = (cx: number, cy: number, length: number, angle: number) => ({
  x: cx + Math.cos(angle) * length,
  y: cy + Math.sin(angle) * length,
});
function dancePose(style: string, name: string, index: number): Pose {
  const p = basePose(360, 720),
    seed = index + Object.keys(danceStyles).indexOf(style) * 11,
    floor =
      /Floor|Freeze|Handstand|Headstand|Crab|Spin Pose|Cartwheel|Split/.test(
        name,
      ),
    ballet =
      /Ballet|Arabesque|Attitude|Leg Extension|Position|Elegant|Leap/.test(
        name,
      ),
    robot = /Robot|Mechanical|Lock|Box Arms|90 Degree|Chest/.test(name),
    lean = ((seed % 7) - 3) * 13,
    spread = 55 + (seed % 5) * 18;
  p.torso.x += lean;
  p.neck.x += lean * 1.3;
  p.head.x += lean * 1.5;
  const ls = p.leftShoulder,
    rs = p.rightShoulder;
  const la = robot
      ? Math.PI + ((seed % 4) * Math.PI) / 2
      : -2.65 + (seed % 6) * 0.42,
    ra = robot ? ((seed % 4) * Math.PI) / 2 : -0.5 - (seed % 7) * 0.38;
  p.leftElbow = point(ls.x, ls.y, 75, la);
  p.leftWrist = point(
    p.leftElbow.x,
    p.leftElbow.y,
    72,
    la + (robot ? 0 : ((seed % 3) - 1) * 0.7),
  );
  p.rightElbow = point(rs.x, rs.y, 75, ra);
  p.rightWrist = point(
    p.rightElbow.x,
    p.rightElbow.y,
    72,
    ra + (robot ? 0 : ((seed % 4) - 1.5) * 0.55),
  );
  p.leftHip = { x: 360 - spread / 2, y: 720 };
  p.rightHip = { x: 360 + spread / 2, y: 720 };
  const legLift = /Kick|Extension|Arabesque|Attitude|One Leg|Balance/.test(
      name,
    ),
    lAng = 1.55 + ((seed % 5) - 2) * 0.22,
    rAng = legLift ? -0.15 - (seed % 3) * 0.25 : 1.55 - ((seed % 5) - 2) * 0.2;
  p.leftKnee = point(p.leftHip.x, p.leftHip.y, 92, lAng);
  p.leftAnkle = point(
    p.leftKnee.x,
    p.leftKnee.y,
    98,
    lAng + ((seed % 3) - 1) * 0.18,
  );
  p.rightKnee = point(p.rightHip.x, p.rightHip.y, 92, rAng);
  p.rightAnkle = point(
    p.rightKnee.x,
    p.rightKnee.y,
    98,
    rAng + (legLift ? -0.2 : ((seed % 3) - 1) * 0.18),
  );
  if (ballet) {
    p.leftWrist.y -= 45;
    p.rightWrist.y -= 45;
    p.leftAnkle.x -= 20;
    p.rightAnkle.x += 25;
  }
  if (floor) {
    for (const j of Object.keys(p) as JointName[]) {
      const q = p[j],
        x = q.x - 360,
        y = q.y - 720;
      q.x = 360 + y * 0.8;
      q.y = 805 + x * 0.45;
    }
    p.root = {
      x: (p.leftHip.x + p.rightHip.x) / 2,
      y: (p.leftHip.y + p.rightHip.y) / 2,
    };
  }
  return p;
}
export const dancePoseEntries = Object.entries(danceStyles).flatMap(
  ([style, names]) =>
    names.map((name, index) => ({
      id: slug(name),
      name,
      category: "Dance" as const,
      style,
      pose: dancePose(style, name, index),
      tags: ["dance", style.toLowerCase(), ...name.toLowerCase().split(" ")],
    })),
);

type DanceActionSpec = [
  string,
  string,
  string,
  string,
  number,
  Action["intensity"],
  boolean?,
  number?,
];
const specs: DanceActionSpec[] = [
  [
    "Techno Basic Loop",
    "Techno",
    "Techno Neutral",
    "Wide Techno Stance",
    4,
    "Medium",
    true,
  ],
  [
    "Techno Bounce Loop",
    "Techno",
    "Bounce High",
    "Techno Neutral",
    4,
    "Medium",
    true,
  ],
  ["Techno Arm Pump Loop", "Techno", "Arm Pump", "Elbow Pump", 4, "High", true],
  [
    "Techno Side Step Loop",
    "Techno",
    "Body Lean Left",
    "Body Lean Right",
    4,
    "Medium",
    true,
  ],
  [
    "Techno Turn",
    "Techno",
    "Techno Neutral",
    "Techno Freeze",
    2,
    "Medium",
    false,
    360,
  ],
  ["Techno Jump", "Techno", "Bounce High", "Techno Freeze", 2, "High"],
  [
    "Techno Freestyle Combination",
    "Techno",
    "Forward Pulse",
    "Double Hand Raise",
    8,
    "High",
  ],
  [
    "Robot Walk",
    "Robot / Popping",
    "Robot Neutral",
    "Mechanical Lean",
    4,
    "Medium",
    true,
  ],
  [
    "Robot Turn",
    "Robot / Popping",
    "Angular Guard",
    "Robot Neutral",
    2,
    "Medium",
    false,
    360,
  ],
  [
    "Robot Head Turn",
    "Robot / Popping",
    "Head Tilt",
    "Robot Neutral",
    2,
    "Low",
  ],
  [
    "Robot Arm Sequence",
    "Robot / Popping",
    "Elbow Lock Left",
    "Elbow Lock Right",
    4,
    "Medium",
    true,
  ],
  [
    "Robot Lock Sequence",
    "Robot / Popping",
    "Double Elbow Lock",
    "Box Arms",
    4,
    "High",
    true,
  ],
  [
    "Chest Pop",
    "Robot / Popping",
    "Chest Back",
    "Chest Forward",
    2,
    "Medium",
    true,
  ],
  [
    "Arm Pop",
    "Robot / Popping",
    "Wrist Angle",
    "Mechanical Reach",
    2,
    "Medium",
    true,
  ],
  [
    "Shoulder Pop",
    "Robot / Popping",
    "Angular Guard",
    "90 Degree Arms",
    2,
    "Medium",
    true,
  ],
  [
    "Mechanical Wave",
    "Robot / Popping",
    "Mechanical Reach",
    "Mechanical Point",
    4,
    "Medium",
    true,
  ],
  [
    "Body Wave",
    "Robot / Popping",
    "Chest Forward",
    "Mechanical Lean",
    4,
    "Medium",
    true,
  ],
  [
    "Robot Freeze",
    "Robot / Popping",
    "High Robot Pose",
    "Freeze Left",
    2,
    "Low",
  ],
  [
    "Toprock Loop",
    "Breakdance",
    "Toprock Neutral",
    "Toprock Cross",
    4,
    "Medium",
    true,
  ],
  ["Floor Entry", "Breakdance", "Drop Preparation", "Floor Entry", 2, "High"],
  ["Kick Out", "Breakdance", "Hand Support", "Kick Out", 2, "High"],
  [
    "Six Step Loop",
    "Breakdance",
    "Two Hand Support",
    "Floor Sweep",
    8,
    "High",
    true,
  ],
  ["Freeze Transition", "Breakdance", "Low Crouch", "Baby Freeze", 4, "High"],
  [
    "Handstand Entry",
    "Breakdance",
    "Headstand Preparation",
    "Handstand",
    4,
    "Acrobatic",
  ],
  [
    "Power Spin",
    "Breakdance",
    "Power Move Preparation",
    "Power Move Extension",
    4,
    "Acrobatic",
    true,
    1080,
  ],
  [
    "Back Spin",
    "Breakdance",
    "Floor Entry",
    "Power Move Extension",
    4,
    "Acrobatic",
    true,
    720,
  ],
  [
    "Acrobatic Exit",
    "Breakdance",
    "One Hand Freeze",
    "Toprock Neutral",
    4,
    "Acrobatic",
  ],
  [
    "Hip Hop Bounce Loop",
    "Hip-Hop",
    "Bounce Down",
    "Bounce Up",
    4,
    "Medium",
    true,
  ],
  [
    "Hip Hop Groove Loop",
    "Hip-Hop",
    "Wide Groove",
    "Low Groove",
    4,
    "Medium",
    true,
  ],
  [
    "Step Touch",
    "Hip-Hop",
    "Step Pose",
    "Cross Step Groove",
    4,
    "Medium",
    true,
  ],
  ["Body Rock", "Hip-Hop", "Lean Left", "Lean Right", 4, "Medium", true],
  ["Hip Hop Freeze Combo", "Hip-Hop", "Open Arms", "Hip-Hop Freeze", 4, "High"],
  [
    "Running Man Loop",
    "Shuffle",
    "Running Man Start",
    "Running Man Extension",
    4,
    "High",
    true,
  ],
  ["T Step Loop", "Shuffle", "T-Step Left", "T-Step Right", 4, "Medium", true],
  ["Shuffle Basic", "Shuffle", "Toe Contact", "Heel Up", 4, "Medium", true],
  [
    "Shuffle Side Travel",
    "Shuffle",
    "Shuffle Slide",
    "Shuffle Cross Step",
    4,
    "High",
    true,
  ],
  [
    "Shuffle Turn",
    "Shuffle",
    "Shuffle Turn",
    "Shuffle Kick",
    4,
    "High",
    false,
    360,
  ],
  [
    "Ballet Walk",
    "Ballet",
    "Neutral Ballet Stand",
    "First Position",
    4,
    "Low",
    true,
  ],
  [
    "Ballet Spin",
    "Ballet",
    "Turn Preparation",
    "Turn Pose",
    4,
    "High",
    false,
    720,
  ],
  [
    "Ballet Leap",
    "Ballet",
    "Leap Preparation",
    "Leap Extension",
    4,
    "Acrobatic",
  ],
  [
    "Arabesque Transition",
    "Ballet",
    "Neutral Ballet Stand",
    "Arabesque Pose",
    4,
    "Medium",
  ],
  [
    "Contemporary Flow",
    "Contemporary",
    "Closed Body",
    "Open Body",
    4,
    "Medium",
    true,
  ],
  [
    "Floor Transition",
    "Contemporary",
    "Floor Reach",
    "Extended Floor Pose",
    4,
    "High",
  ],
  [
    "Retro Groove",
    "Disco / Retro",
    "Hip Shift",
    "Disco Point Up",
    4,
    "Medium",
    true,
  ],
  [
    "Celebration Loop",
    "Celebration / Party",
    "Party Bounce",
    "Party Hands Up",
    4,
    "High",
    true,
  ],
  [
    "Partner Side Step",
    "Partner Dance",
    "Partner Hold",
    "Side Step Together",
    4,
    "Low",
    true,
  ],
  [
    "Partner Turn",
    "Partner Dance",
    "Partner Hold",
    "Underarm Turn",
    4,
    "Medium",
    false,
    360,
  ],
  [
    "Slow Dance",
    "Slow Dance",
    "Slow Sway Left",
    "Slow Sway Right",
    8,
    "Low",
    true,
  ],
];
export const danceActions: Action[] = specs.map(
  ([
    name,
    style,
    entry,
    main,
    beats,
    intensity,
    loopable = false,
    rotation,
  ]) => {
    const entryPose = slug(entry),
      mainPose = slug(main),
      duration = beats * 0.5;
    return {
      id: slug(name),
      name,
      categories: ["Dance"],
      subcategory: style,
      style,
      tags: ["dance", style.toLowerCase(), name.toLowerCase()],
      participants: /Partner|Slow Dance/.test(name)
        ? ["actor", "actor"]
        : ["actor"],
      duration,
      beats,
      bars: beats / 4,
      intensity,
      loopable,
      entryPose,
      mainPose,
      exitPose: entryPose,
      keyframes: [
        {
          time: 0,
          pose: entryPose,
          easing: style === "Robot / Popping" ? "hold" : "ease-in-out",
        },
        {
          time: duration / 2,
          pose: mainPose,
          easing: style === "Robot / Popping" ? "snap" : "ease-in-out",
          ...(/Leap|Jump/.test(name) ? { dy: -180 } : {}),
        },
        {
          time: duration,
          pose: entryPose,
          easing: style === "Robot / Popping" ? "linear" : "ease-in-out",
          ...(rotation ? { rootRotation: rotation } : {}),
          ...(/Travel|Walk/.test(name)
            ? { dx: 220 }
            : /Leap/.test(name)
              ? { dx: 180 }
              : {}),
        },
      ],
    };
  },
);
