import { useMemo, useState } from "react";
import { insertAction, loadActionAssets } from "./actionAssets";
import { buildFight, builtInFightPackages, fightMoves, type FightPackage, type FightSettings } from "./fightDirector";
import type { Project } from "./types";
import { FightMovePreview } from "./FightMovePreview";

const PACKAGE_KEY="flip-studio-fight-packages-v1";
const loadPackages=():FightPackage[]=>{try{return JSON.parse(localStorage.getItem(PACKAGE_KEY)||"[]")}catch{return[]}};
export function FightDirectorPanel({project,playhead,onClose,onApply}:{project:Project;playhead:number;onClose:()=>void;onApply:(p:Project)=>void}){
 const [category,setCategory]=useState("All"),[search,setSearch]=useState(""),[cart,setCart]=useState<string[]>([]),[attacker,setAttacker]=useState(project.characters[0]?.id??""),[target,setTarget]=useState(project.characters[1]?.id??""),[packages,setPackages]=useState(loadPackages);
 const [settings,setSettings]=useState<FightSettings>({duration:30,style:"Arcade",intensity:.75,specials:true,grapples:true,aerial:true,projectiles:true,autoCamera:true,winner:"Auto",seed:1741,combatType:"UNARMED",attackerWeapon:"None",targetWeapon:"None",attackerHand:"right",targetHand:"right",swordStrength:"AUTO",weaponTrail:true,cinematicMode:"STANDARD"});
 const categories=["All",...new Set(fightMoves.map(m=>m.category))],shown=useMemo(()=>fightMoves.filter(m=>(settings.combatType==="MIXED"||(settings.combatType==="SWORD"?m.tags.includes("sword"):!m.tags.includes("sword")))&&(!m.tags.includes("sword")||!settings.swordStrength||settings.swordStrength==="AUTO"||m.tags.includes(settings.swordStrength.toLowerCase()))&&(category==="All"||m.category===category)&&(`${m.name} ${m.tags.join(" ")}`.toLowerCase().includes(search.toLowerCase()))),[category,search,settings.combatType,settings.swordStrength]);
 const customActions=loadActionAssets().filter(a=>[a.category,...a.tags].some(x=>/fight|combo|special|reaction|grapple|aerial/i.test(x)));
 const run=(ids:string[]=[])=>{if(project.characters.length<2||!attacker||!target||attacker===target){alert("Fight Director needs two different characters. Add two characters from the Scene panel, then choose Attacker and Target.");return}onApply(buildFight(project,attacker,target,playhead,{...settings,duration:ids.length?Math.max(3,ids.reduce((n,id)=>n+(fightMoves.find(m=>m.id===id)?.duration??0)+.3,0)+1.8):settings.duration},ids));onClose()};
 const choosePackage=(id:string)=>{const pkg=[...builtInFightPackages,...packages].find(x=>x.id===id);if(pkg)setSettings(s=>({...s,...pkg.settings,packageId:id}));};
 const savePackage=()=>{const pkg:FightPackage={id:crypto.randomUUID(),name:`My ${settings.style} Package`,description:"Saved Fight Director configuration",settings:{...settings}};const next=[...packages,pkg];setPackages(next);localStorage.setItem(PACKAGE_KEY,JSON.stringify(next));};
 return <div className="fight-backdrop"><section className="fight-workspace"><header><div><b>⚔ FIGHT DIRECTOR</b><small>Range-aware choreography · deterministic phases · deliberate endings</small></div><button onClick={onClose}>×</button></header><div className="fight-body"><aside><div className="fight-settings-scroll"><h2>Generate Fight</h2>
 <label>Package<select value={settings.packageId??""} onChange={e=>choosePackage(e.target.value)}><option value="">Custom</option>{[...builtInFightPackages,...packages].map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button onClick={savePackage}>SAVE PACKAGE</button>
 <label>Attacker<select value={attacker} onChange={e=>setAttacker(e.target.value)}>{project.characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Target<select value={target} onChange={e=>setTarget(e.target.value)}>{project.characters.filter(c=>c.id!==attacker).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label>Combat Type<select value={settings.combatType} onChange={e=>{const combatType=e.target.value as FightSettings["combatType"];setSettings({...settings,combatType,attackerWeapon:combatType==="UNARMED"?"None":"Sword",targetWeapon:combatType==="SWORD"?"Sword":"None"})}}><option value="UNARMED">Unarmed</option><option value="SWORD">Sword Duel</option><option value="MIXED">Mixed</option></select></label>
 {settings.combatType!=="UNARMED"&&<><div className="fight-grid"><label>Attacker Weapon<select value={settings.attackerWeapon} onChange={e=>setSettings({...settings,attackerWeapon:e.target.value as "None"|"Sword"})}><option>None</option><option>Sword</option></select></label><label>Attacker Hand<select value={settings.attackerHand} onChange={e=>setSettings({...settings,attackerHand:e.target.value as "left"|"right"})}><option value="right">Right</option><option value="left">Left</option></select></label></div><div className="fight-grid"><label>Target Weapon<select value={settings.targetWeapon} onChange={e=>setSettings({...settings,targetWeapon:e.target.value as "None"|"Sword"})}><option>None</option><option>Sword</option></select></label><label>Target Hand<select value={settings.targetHand} onChange={e=>setSettings({...settings,targetHand:e.target.value as "left"|"right"})}><option value="right">Right</option><option value="left">Left</option></select></label></div><div className="fight-grid"><label>Sword Strength<select value={settings.swordStrength} onChange={e=>setSettings({...settings,swordStrength:e.target.value as FightSettings["swordStrength"]})}>{["AUTO","LIGHT","MEDIUM","HEAVY","SPECIAL"].map(x=><option key={x}>{x}</option>)}</select></label><label>Cinematic<select value={settings.cinematicMode} onChange={e=>setSettings({...settings,cinematicMode:e.target.value as FightSettings["cinematicMode"]})}><option value="STANDARD">Standard</option><option value="DRAMATIC">Dramatic</option></select></label></div><label className="fight-check"><input type="checkbox" checked={settings.weaponTrail!==false} onChange={e=>setSettings({...settings,weaponTrail:e.target.checked})}/>Sword Trail</label></>}
 <div className="fight-grid"><label>Duration<select value={settings.duration} onChange={e=>setSettings({...settings,duration:+e.target.value})}>{[10,15,20,30,60].map(x=><option key={x}>{x}</option>)}</select></label><label>Style<select value={settings.style} onChange={e=>setSettings({...settings,style:e.target.value as FightSettings["style"]})}>{["Balanced","Fast","Technical","Acrobatic","Arcade","Heavy"].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <label>Intensity {Math.round(settings.intensity*100)}%<input type="range" min="0" max="1" step=".05" value={settings.intensity} onChange={e=>setSettings({...settings,intensity:+e.target.value})}/></label>{(["specials","grapples","aerial","projectiles","autoCamera"] as const).map(k=><label className="fight-check" key={k}><input type="checkbox" checked={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.checked})}/>{k.replace(/([A-Z])/g," $1")}</label>)}
 <label>Winner<select value={settings.winner} onChange={e=>setSettings({...settings,winner:e.target.value as FightSettings["winner"]})}>{["Auto","Fighter A","Fighter B","No Winner"].map(x=><option key={x}>{x}</option>)}</select></label><label>Seed<input type="number" value={settings.seed} onChange={e=>setSettings({...settings,seed:+e.target.value})}/></label>
 <div className="fight-cart"><h3>Fight Cart <small>{cart.length}</small></h3>{cart.map((id,i)=><div draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=+e.dataTransfer.getData("text/plain");setCart(current=>{const next=[...current],moved=next.splice(from,1)[0];next.splice(i,0,moved);return next})}} key={`${id}-${i}`}><span>↕ {i+1}. {fightMoves.find(m=>m.id===id)?.name}</span><button onClick={()=>setCart(c=>c.filter((_,n)=>n!==i))}>×</button></div>)}</div></div><div className="fight-actions-footer">{cart.length>0?<><button onClick={()=>setCart([])}>Clear</button><button className="fight-sequence" onClick={()=>run(cart)}>ADD SEQUENCE TO TIMELINE</button></>:<button onClick={()=>setSettings({...settings,seed:settings.seed+1})}>↻ New Seed</button>}<button className="fight-generate" onClick={()=>run()}>GENERATE FIGHT</button></div></aside>
 <main><div className="fight-tools"><input placeholder="Search moves…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{fightMoves.length} coordinated moves</span></div><nav>{categories.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</nav><div className="fight-cards">{shown.map(m=><article key={m.id}><FightMovePreview move={m} settings={settings}/><strong>{m.name}</strong><p>{m.description}</p><small>{m.category} · {m.duration.toFixed(2)}s · {m.range}</small><div><button onClick={()=>run([m.id])}>Apply Move</button><button onClick={()=>setCart(c=>[...c,m.id])}>＋ Cart</button></div></article>)}</div>
 {customActions.length>0&&<><h2>My Fight Actions</h2><div className="fight-cards">{customActions.map(a=><article key={a.id}><div className="fight-preview">{a.actorCount>1?"● ⇄ ●":"●╱"}</div><strong>{a.name}</strong><small>{a.category} · {a.duration.toFixed(2)}s</small><button onClick={()=>{onApply(insertAction(project,a,a.actorCount>1?[attacker,target]:[attacker],playhead));onClose()}}>Apply Action</button></article>)}</div></>}
 </main></div></section></div>;
}
