import {clonePose, joints, poseAt, propTransformAt, transformAt, uid} from "./animation";
import type {MotionPath,MotionPathDensity,MotionPathPoint,Project,V} from "./types";
export function detachMotionPathKey(key:{source?:string;motionPathId?:string}){if(key.source==="MOTION_PATH"){key.source="MOTION_PATH_MODIFIED";delete key.motionPathId}}

const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const pathEase=(t:number,e:MotionPath["easing"])=>e==="ease-in"?t*t:e==="ease-out"?1-(1-t)*(1-t):e==="ease-in-out"?(t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2):t;
const lerp=(a:V,b:V,t:number):V=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
const cubic=(a:V,c1:V,c2:V,b:V,t:number):V=>{const u=1-t;return{x:u*u*u*a.x+3*u*u*t*c1.x+3*u*t*t*c2.x+t*t*t*b.x,y:u*u*u*a.y+3*u*u*t*c1.y+3*u*t*t*c2.y+t*t*t*b.y}};
const controls=(a:MotionPathPoint,b:MotionPathPoint)=>({c1:a.out??lerp(a,b,1/3),c2:b.in??lerp(a,b,2/3)});
export function rawPoint(path:MotionPath,segment:number,t:number):V{const a=path.points[segment],b=path.points[segment+1];if(!a||!b)return path.points[0]??{x:0,y:0};if(path.pathType==="bezier"||path.pathType==="free-draw"){const {c1,c2}=controls(a,b);return cubic(a,c1,c2,b,t)}return lerp(a,b,t)}
export type PathLookup={distance:number;point:V;segment:number;t:number}[];
export function pathLookup(path:MotionPath,steps=32):PathLookup{const out:PathLookup=[];let distance=0,last:V|undefined;for(let s=0;s<path.points.length-1;s++){const curved=path.pathType==="bezier"||path.pathType==="free-draw",count=curved?steps:1;for(let i=0;i<=count;i++){if(s&&i===0)continue;const point=rawPoint(path,s,i/count);if(last)distance+=Math.hypot(point.x-last.x,point.y-last.y);out.push({distance,point,segment:s,t:i/count});last=point}}return out}
export function pointAtPath(path:MotionPath,progress:number){const table=pathLookup(path),total=table.at(-1)?.distance??0,target=clamp(progress)*total;if(!table.length)return{x:0,y:0,tangent:{x:1,y:0}};let i=1;while(i<table.length&&table[i].distance<target)i++;const a=table[Math.max(0,i-1)],b=table[Math.min(i,table.length-1)],span=Math.max(.00001,b.distance-a.distance),p=lerp(a.point,b.point,(target-a.distance)/span),before=table[Math.max(0,i-2)]?.point??a.point,after=table[Math.min(table.length-1,i+1)]?.point??b.point;return{...p,tangent:{x:after.x-before.x,y:after.y-before.y}}}
export function pointAtTime(path:MotionPath,time:number){const progress=clamp((time-path.startTime)/Math.max(.001,path.endTime-path.startTime));return pointAtPath(path,pathEase(progress,path.easing))}

export function simplifyFreeDraw(raw:V[],tolerance=7):V[]{if(raw.length<3)return raw;const sq=tolerance*tolerance;const recurse=(points:V[],first:number,last:number,out:V[])=>{let max=sq,index=-1,a=points[first],b=points[last],dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;for(let i=first+1;i<last;i++){let t=l2?clamp(((points[i].x-a.x)*dx+(points[i].y-a.y)*dy)/l2):0,px=a.x+t*dx,py=a.y+t*dy,d=(points[i].x-px)**2+(points[i].y-py)**2;if(d>max){index=i;max=d}}if(index>0){recurse(points,first,index,out);out.push(points[index]);recurse(points,index,last,out)}};const out=[raw[0]];recurse(raw,0,raw.length-1,out);out.push(raw.at(-1)!);return out}
export function smoothPoints(points:V[]):MotionPathPoint[]{return points.map((p,i)=>{const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],dx=(next.x-prev.x)/6,dy=(next.y-prev.y)/6;return{id:uid(),...p,...(i?{in:{x:p.x-dx,y:p.y-dy}}:{}),...(i<points.length-1?{out:{x:p.x+dx,y:p.y+dy}}:{})}})}
export function createMotionPath(project:Project,targetId:string,targetType:"character"|"prop",type:MotionPath["pathType"],startTime:number):MotionPath{const start=targetType==="character"?poseAt(project.tracks[targetId]??[],startTime).root:propTransformAt(project.propTracks?.[targetId],startTime),end={x:start.x+Math.min(300,project.format.width*.25),y:start.y};const now=new Date().toISOString(),points:MotionPathPoint[]=[{id:uid(),x:start.x,y:start.y},{id:uid(),x:end.x,y:end.y}];if(type==="bezier"){points[0].out={x:start.x+100,y:start.y-130};points[1].in={x:end.x-100,y:end.y-130}}return{id:`path_${uid()}`,name:`Path ${(project.motionPaths?.length??0)+1}`,targetId,targetType,pathType:type,points,startTime,endTime:Math.min(project.duration,startTime+1),easing:"ease-in-out",orientToPath:false,density:"medium",visible:true,createdAt:now,updatedAt:now}}
const spacing=(d:MotionPathDensity)=>d==="low"?.25:d==="high"?.065:.125;
export function pathTimes(path:MotionPath){const duration=path.endTime-path.startTime,count=Math.max(1,Math.ceil(duration/spacing(path.density)));return Array.from({length:count+1},(_,i)=>+(path.startTime+duration*i/count).toFixed(4))}
export function rootConflict(project:Project,path:MotionPath){if(path.targetType!=="character")return false;const authored=(project.tracks[path.targetId]??[]).filter(k=>k.time>=path.startTime-.001&&k.time<=path.endTime+.001&&k.source!=="MOTION_PATH");if(authored.length<2)return false;const root=authored[0].pose.root;return authored.some(k=>Math.hypot(k.pose.root.x-root.x,k.pose.root.y-root.y)>1)}
export function bakeMotionPath(project:Project,path:MotionPath):Project{if(path.endTime<=path.startTime)throw new Error("End Time must be after Start Time.");if(path.points.length<2)throw new Error("Path needs at least two points.");if(rootConflict(project,path))throw new Error("Existing authored root motion exists in this range. Path bake was cancelled to protect it.");const next=structuredClone(project),times=pathTimes(path);if(path.targetType==="character"){const track=(next.tracks[path.targetId]??=[]).filter(k=>k.motionPathId!==path.id||k.source!=="MOTION_PATH");let facing=transformAt(track,path.startTime).flipH;const generated=times.map(time=>{const pose=clonePose(poseAt(track,time)),sample=pointAtTime(path,time),dx=sample.x-pose.root.x,dy=sample.y-pose.root.y;for(const j of joints){pose[j].x+=dx;pose[j].y+=dy}if(path.orientToPath&&!next.fights?.some(f=>time>=f.startTime&&time<=f.endTime)&&Math.abs(sample.tangent.x)>4)facing=sample.tangent.x<0;const tf=transformAt(track,time);return{id:uid(),time,pose,easing:"linear" as const,rotation:tf.rotation,scaleX:tf.scaleX,scaleY:tf.scaleY,flipH:facing,flipV:tf.flipV,source:"MOTION_PATH" as const,motionPathId:path.id}});next.tracks[path.targetId]=[...track,...generated].sort((a,b)=>a.time-b.time)}else{next.propTracks??={};const track=(next.propTracks[path.targetId]??[]).filter(k=>k.motionPathId!==path.id||k.source!=="MOTION_PATH"),generated=times.map(time=>{const tf=propTransformAt(track,time),sample=pointAtTime(path,time),rotation=path.orientToPath?Math.atan2(sample.tangent.y,sample.tangent.x)*180/Math.PI:tf.rotation;return{...tf,id:uid(),time,x:sample.x,y:sample.y,rotation,easing:"linear" as const,source:"MOTION_PATH" as const,motionPathId:path.id}});next.propTracks[path.targetId]=[...track,...generated].sort((a,b)=>a.time-b.time)}return next}
export function previewPathProject(project:Project,path:MotionPath,time:number){if(time<path.startTime||time>path.endTime)return project;const next=structuredClone(project),sample=pointAtTime(path,time);if(path.targetType==="character"){const track=next.tracks[path.targetId]??[],pose=clonePose(poseAt(track,time)),dx=sample.x-pose.root.x,dy=sample.y-pose.root.y;for(const j of joints){pose[j].x+=dx;pose[j].y+=dy}next.tracks[path.targetId]=[{id:"preview",time,pose,easing:"linear",...transformAt(track,time)}]}else{next.propTracks??={};next.propTracks[path.targetId]=[{id:"preview",time,easing:"linear",...propTransformAt(next.propTracks[path.targetId],time),x:sample.x,y:sample.y}]}return next}
