import {useState} from "react";
import type {MotionPath,MotionPathType,Project} from "./types";
import {rootConflict} from "./motionPath";

export function PathPanel({project,selectedPath,targetId,targetType,playhead,onSelect,onNew,onChange,onDuplicate,onDelete,onPreview,onBake,previewing,editing,onEditingChange,onVisibilityChange}:{
 project:Project;selectedPath:string|null;targetId:string;targetType:"character"|"prop";onSelect:(id:string|null)=>void;
 playhead:number;onNew:(type:MotionPathType)=>void;onChange:(path:MotionPath)=>void;onDuplicate:()=>void;onDelete:()=>void;onPreview:()=>void;onBake:()=>void;previewing:boolean;editing:boolean;onEditingChange:(value:boolean)=>void;onVisibilityChange:(value:NonNullable<Project["pathVisibility"]>)=>void;
}){
 const [message,setMessage]=useState<{kind:"ok"|"error";text:string}|null>(null);
 const paths=project.motionPaths??[],path=paths.find(x=>x.id===selectedPath),targets=[...project.characters.map(x=>({id:x.id,name:x.name,type:"character" as const})),...(project.props??[]).map(x=>({id:x.id,name:x.name,type:"prop" as const}))];
 const change=(values:Partial<MotionPath>)=>path&&onChange({...path,...values,updatedAt:new Date().toISOString()});
 const setBoundary=(kind:"in"|"out")=>{if(!path)return;if(kind==="in"&&playhead>=path.endTime){setMessage({kind:"error",text:"Cannot set IN at or after OUT."});return}if(kind==="out"&&playhead<=path.startTime){setMessage({kind:"error",text:"OUT must be later than IN."});return}change(kind==="in"?{startTime:playhead}:{endTime:playhead});setMessage({kind:"ok",text:`✓ ${kind.toUpperCase()} set to ${playhead.toFixed(3)}s`})};
 return <section className="path-panel">
  <div className="path-list-head"><b>PATHS</b><select aria-label="Stage Paths" value={project.pathVisibility??"selected"} onChange={e=>onVisibilityChange(e.target.value as NonNullable<Project["pathVisibility"]>)}><option value="selected">Selected Only</option><option value="all">All Paths</option><option value="hidden">Hide Paths</option></select></div>
  <div className="path-list">{paths.map(x=><button className={x.id===selectedPath?"active":""} key={x.id} onClick={()=>onSelect(x.id)}><span>◆ {x.name}</span><small>{targets.find(t=>t.id===x.targetId)?.name??x.targetId}</small></button>)}</div>
  {!path?<div className="path-empty"><b>Create spatial movement</b><p>Create a motion path for the selected Character or Object.</p><label>Target<strong>{targets.find(x=>x.id===targetId)?.name??"Select a target"}</strong></label><div className="path-new-grid">{(["straight","bezier","polyline","free-draw"] as MotionPathType[]).map(type=><button key={type} disabled={!targetId} onClick={()=>onNew(type)}>＋ {type.replace("-"," ")}</button>)}</div></div>:<>
   <div className="path-summary"><input aria-label="Path name" value={path.name} onChange={e=>change({name:e.target.value})}/><small>{targets.find(t=>t.id===path.targetId)?.name} · {path.pathType}</small></div>
   <div className="path-timing-card"><b>PATH RANGE</b><div className="path-range-visual"><span>{path.startTime.toFixed(3)}s</span><i/><span>{path.endTime.toFixed(3)}s</span></div><strong>{path.name}</strong><div className="path-range-values"><span><small>IN</small><b>{path.startTime.toFixed(3)}s</b></span><span><small>OUT</small><b>{path.endTime.toFixed(3)}s</b></span><span><small>DURATION</small><b>{Math.max(0,path.endTime-path.startTime).toFixed(3)}s</b></span></div><div><button onClick={()=>setBoundary("in")}>◀ Set IN</button><button onClick={()=>setBoundary("out")}>Set OUT ▶</button></div><p>Move the playhead, then set IN or OUT.</p>{message&&<output className={`path-feedback ${message.kind}`}>{message.text}</output>}<details><summary>▸ Exact Time</summary><div className="grid"><label>IN<input type="number" min="0" max={project.duration} step=".001" value={path.startTime} onChange={e=>change({startTime:+e.target.value})}/></label><label>OUT<input type="number" min="0" max={project.duration} step=".001" value={path.endTime} onChange={e=>change({endTime:+e.target.value})}/></label></div></details></div>
   <section className="path-group"><h4>SHAPE</h4><label>Type<select value={path.pathType} onChange={e=>change({pathType:e.target.value as MotionPathType})}><option value="straight">Straight</option><option value="polyline">Polyline</option><option value="bezier">Bezier</option><option value="free-draw">Free Draw</option></select></label><button className={editing?"path-edit-toggle active":"path-edit-toggle"} onClick={()=>onEditingChange(!editing)}>{editing?"✓ Finish Editing":"✎ Edit Path"}</button></section>
   <section className="path-group"><h4>MOTION</h4>
   <label>Timing / Easing<select value={path.easing} onChange={e=>change({easing:e.target.value as MotionPath["easing"]})}><option value="linear">Linear / Constant</option><option value="ease-in">Ease In</option><option value="ease-out">Ease Out</option><option value="ease-in-out">Ease In-Out</option></select></label>
   <label>Motion Density<select value={path.density} onChange={e=>change({density:e.target.value as MotionPath["density"]})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>
   {path.targetType==="character"&&<div className="path-options"><button title="Automatically face the Character in the direction of travel." className={path.orientToPath?"active":""} onClick={()=>change({orientToPath:!path.orientToPath})}><span>↗ Face Along Path</span><b>{path.orientToPath?"ON":"OFF"}</b></button></div>}
   </section>
   {rootConflict(project,path)&&<div className="path-warning">Existing authored root motion exists in this range. Bake is protected.</div>}
   <section className="path-group"><h4>PLAYBACK</h4><div className="path-actions"><button className={previewing?"active":""} disabled={path.endTime<=path.startTime} onClick={onPreview}>{previewing?"■ Stop":"▶ Preview"}</button><button className="path-bake" disabled={path.endTime<=path.startTime||rootConflict(project,path)} onClick={onBake}>◆ Bake to Timeline</button></div></section>
   <div className="grid"><button onClick={onDuplicate}>⧉ Duplicate</button><button className="danger" onClick={onDelete}>Delete Path</button></div>
   <small className="format-readout">Enable Edit Path before dragging anchors/handles. Move/Pose tools stay reserved for the character.</small>
  </>}
 </section>
}
