import {actions} from "./actions";
import {cameraAt,clonePose,poseAt,uid} from "./animation";
import {addCombatFx,combatFxPresets} from "./combatFx";
import {applyFightMoveSequence,applyReactionMove,fightMoves,type FightExecutionMode,type FightSettings} from "./fightDirector";
import {orientedPose,poseCatalog,poses,type PoseOrientation} from "./poses";
import type {CameraState,Ease,Pose,Project} from "./types";

export type CommandTime={time?:number;timeMs?:number};
type ReplaceRange={start?:number;end?:number;startMs?:number;endMs?:number};
export type TimelineCommand=
 | ({type:"POSE";actor:string;name:string;orientation?:PoseOrientation;easing?:Ease}&CommandTime)
 | ({type:"ACTION";actor:string;name:string}&CommandTime)
 | ({type:"FIGHT_MOVE";attacker:string;target?:string;name:string;execution?:"ATTACKER_ONLY"|"PAIRED"|"attacker-only"|"paired"}&CommandTime)
 | ({type:"REACTION";actor:string;name:string}&CommandTime)
 | ({type:"CAMERA";name?:string;values?:Partial<CameraState>;actor?:string}&CommandTime)
 | ({type:"EFFECT";name:string;actor?:string;x?:number;y?:number}&CommandTime)
 | ({type:"MOVE_ACTOR";actor:string;x?:number;y?:number;dx?:number;dy?:number;easing?:Ease}&CommandTime)
 | ({type:"SET_FACING";actor:string;facing:"LEFT"|"RIGHT";target?:string}&CommandTime);
export interface TimelineSequence{duration?:number;durationMs?:number;replaceRange?:ReplaceRange;commands:TimelineCommand[]}
export interface TimelineApplyResult{project:Project;inserted:{command:number;kind:TimelineCommand["type"];time:number;ids:string[]}[]}

export const cameraCommandPresets:Record<string,{name:string;zoom?:number;rotation?:number}>={
  "level":{name:"Level",zoom:1,rotation:0},"dutch_l":{name:"Dutch L",rotation:-10},"dutch_r":{name:"Dutch R",rotation:10},
  "strong_l":{name:"Strong L",rotation:-20},"strong_r":{name:"Strong R",rotation:20},"wide_both":{name:"Wide Both",zoom:.7},
  "push_in":{name:"Push In",zoom:1.08},"impact_push":{name:"Impact Push",zoom:1.15},"airborne_follow":{name:"Airborne Follow",zoom:.85},
} as const;

const norm=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
const seconds=(value:CommandTime,label="command")=>{const hasS=value.time!==undefined,hasMs=value.timeMs!==undefined;if(hasS===hasMs)throw new Error(`${label} must provide exactly one of time or timeMs`);const time=hasMs?value.timeMs!/1000:value.time!;if(!Number.isFinite(time)||time<0)throw new Error(`${label} time must be a non-negative number`);return Math.round(time*1e6)/1e6};
const distance=(a:string,b:string)=>{const rows=Array.from({length:a.length+1},(_,i)=>[i,...Array(b.length).fill(0)]);for(let j=1;j<=b.length;j++)rows[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)rows[i][j]=Math.min(rows[i-1][j]+1,rows[i][j-1]+1,rows[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return rows[a.length][b.length]};
const closest=(input:string,items:{id?:string;name:string}[])=>[...items].sort((a,b)=>distance(norm(input),norm(a.name))-distance(norm(input),norm(b.name))).slice(0,3).map(x=>x.name);
const resolve=<T extends {id?:string;name:string}>(input:string,items:T[],kind:string):T=>{const key=norm(input),item=items.find(x=>(x.id&&norm(x.id)===key)||norm(x.name)===key);if(item)return item;const suggestions=closest(input,items);throw new Error(`Unknown ${kind} "${input}"${suggestions.length?`\nClosest matches:\n${suggestions.map(x=>`- ${x}`).join("\n")}`:""}`)};
const actorItems=(p:Project)=>p.characters.map(x=>({id:x.id,name:x.name}));
const actor=(p:Project,value:string)=>resolve(value,actorItems(p),"Actor").id;
const poseItems=()=>{const items=poseCatalog.map(x=>({id:x.id,name:x.name}));for(const id of Object.keys(poses))if(!items.some(x=>x.id===id))items.push({id,name:id});return items};
const reactionItems=()=>fightMoves.filter(x=>x.category==="Reaction");
const defaultFight:FightSettings={duration:5,style:"Balanced",intensity:.65,specials:true,grapples:true,aerial:true,projectiles:true,autoCamera:false,winner:"No Winner",seed:1741,combatType:"UNARMED",attackerWeapon:"None",targetWeapon:"None",weaponTrail:true,cinematicMode:"STANDARD"};
const shift=(source:Pose,dx:number,dy=0)=>{const p=clonePose(source);Object.values(p).forEach(q=>{q.x+=dx;q.y+=dy});return p};
const mirror=(source:Pose)=>{const p=clonePose(source),x=p.root.x;Object.values(p).forEach(q=>q.x=x-(q.x-x));return p};
const isFacingLeft=(p:Pose)=>(p.head.x-p.root.x)+(p.torso.x-p.root.x)*.8+(((p.leftWrist.x+p.rightWrist.x)/2)-p.root.x)*.35<0;
const keyIds=(before:Project,after:Project)=>{const old=new Set<string>();Object.values(before.tracks).flat().forEach(k=>old.add(k.id));before.camera.forEach(k=>old.add(k.id));before.effects.forEach(k=>old.add(k.id));return [...Object.values(after.tracks).flat(),...after.camera,...after.effects].filter(k=>!old.has(k.id)).map(k=>k.id)};

function validateDetailed(project:Project,sequence:TimelineSequence){const errors:string[]=[];sequence.commands.forEach((command,index)=>{try{seconds(command,`Command ${index+1}`);if("actor" in command&&command.actor)actor(project,command.actor);if(command.type==="POSE"){resolve(command.name,poseItems(),"Pose");if(command.orientation&&!(["FRONT","THREE_QUARTER_LEFT","SIDE_LEFT","THREE_QUARTER_RIGHT","SIDE_RIGHT"] as string[]).includes(command.orientation))throw new Error(`Unknown orientation "${command.orientation}"`)}else if(command.type==="ACTION")resolve(command.name,actions,"Action");else if(command.type==="FIGHT_MOVE"){actor(project,command.attacker);if(command.target)actor(project,command.target);resolve(command.name,fightMoves,"Fight Move");const execution=norm(command.execution??"PAIRED");if(execution!=="attacker_only"&&execution!=="paired")throw new Error(`Unknown execution "${command.execution}"`);if(execution==="paired"&&!command.target)throw new Error("PAIRED fight move requires target");}else if(command.type==="REACTION")resolve(command.name,reactionItems(),"Reaction");else if(command.type==="EFFECT")resolve(command.name,combatFxPresets,"Effect");else if(command.type==="CAMERA"&&command.name)resolve(command.name,Object.entries(cameraCommandPresets).map(([id,x])=>({id,name:x.name})),"Camera preset");}catch(error){errors.push(`Command ${index+1}:\n${error instanceof Error?error.message:String(error)}`)}});return errors}
export function validateTimelineSequence(project:Project,sequence:TimelineSequence){const errors=validateDetailed(project,sequence);return errors.length?`ERROR\n${errors.join("\n\n")}`:"VALID"}

function clearRange(p:Project,range:ReplaceRange){const start=range.startMs!==undefined?range.startMs/1000:(range.start??0),end=range.endMs!==undefined?range.endMs/1000:(range.end??start);for(const id of Object.keys(p.tracks))p.tracks[id]=p.tracks[id].filter(k=>k.time<start||k.time>end);p.camera=p.camera.filter(k=>k.time<start||k.time>end);p.effects=p.effects.filter(k=>k.time<start||k.time>end)}
export function applyTimelineSequence(project:Project,sequence:TimelineSequence):TimelineApplyResult{const validation=validateTimelineSequence(project,sequence);if(validation!=="VALID")throw new TimelineCommandError(validation);let p=structuredClone(project);if(sequence.replaceRange)clearRange(p,sequence.replaceRange);const inserted:TimelineApplyResult["inserted"]=[];
  sequence.commands.forEach((command,index)=>{const time=seconds(command),before=structuredClone(p);
    if(command.type==="POSE"){const id=actor(p,command.actor),item=resolve(command.name,poseItems(),"Pose"),current=poseAt(p.tracks[id],time),source=command.orientation?orientedPose(poses[item.id!],command.orientation):poses[item.id!],q=shift(source,current.root.x-source.root.x,current.root.y-source.root.y);p.tracks[id].push({id:uid(),time,pose:q,easing:command.easing??"ease-in-out"});p.tracks[id].sort((a,b)=>a.time-b.time)}
    else if(command.type==="ACTION"){const id=actor(p,command.actor),action=resolve(command.name,actions,"Action"),origin=poseAt(p.tracks[id],time).root,left=p.characters.find(x=>x.id===id)?.flip??false;for(const frame of action.keyframes.filter(x=>x.actorIndex===undefined||x.actorIndex===0)){let q=clonePose(poses[frame.pose]??poses.neutral_stand);if(left)q=mirror(q);q=shift(q,origin.x-q.root.x+(frame.dx??0)*(left?-1:1),origin.y-q.root.y+(frame.dy??0));p.tracks[id].push({id:uid(),time:time+frame.time,pose:q,easing:frame.easing})}p.tracks[id].sort((a,b)=>a.time-b.time);p.duration=Math.max(p.duration,time+action.duration)}
    else if(command.type==="FIGHT_MOVE"){const attackerId=actor(p,command.attacker),targetId=command.target?actor(p,command.target):undefined,move=resolve(command.name,fightMoves,"Fight Move"),execution:FightExecutionMode=norm(command.execution??"PAIRED")==="attacker_only"?"ATTACKER_ONLY":"ATTACK_REACTION";p=applyFightMoveSequence(p,attackerId,targetId,time,defaultFight,[move.id],execution,true)}
    else if(command.type==="REACTION"){const id=actor(p,command.actor),move=resolve(command.name,reactionItems(),"Reaction");p=applyReactionMove(p,id,time,move)}
    else if(command.type==="CAMERA"){const current=cameraAt(p.camera,time),preset=command.name?resolve(command.name,Object.entries(cameraCommandPresets).map(([id,x])=>({id,name:x.name})),"Camera preset"):undefined,values=preset?cameraCommandPresets[preset.id as keyof typeof cameraCommandPresets]:undefined,focus=command.actor?poseAt(p.tracks[actor(p,command.actor)],time).root:undefined;p.camera.push({id:uid(),time,x:focus?.x??command.values?.x??current.x,y:focus?.y??command.values?.y??current.y,zoom:command.values?.zoom??values?.zoom??current.zoom,rotation:command.values?.rotation??values?.rotation??current.rotation,easing:"ease-in-out"});p.camera.sort((a,b)=>a.time-b.time)}
    else if(command.type==="EFFECT"){const id=command.actor?actor(p,command.actor):undefined,preset=resolve(command.name,combatFxPresets,"Effect");p=addCombatFx(p,preset,id,time,command.x!==undefined&&command.y!==undefined?{x:command.x,y:command.y}:undefined)}
    else if(command.type==="MOVE_ACTOR"){const id=actor(p,command.actor),current=poseAt(p.tracks[id],time),x=command.x??current.root.x+(command.dx??0),y=command.y??current.root.y+(command.dy??0),q=shift(current,x-current.root.x,y-current.root.y);p.tracks[id].push({id:uid(),time,pose:q,easing:command.easing??"ease-in-out"});p.tracks[id].sort((a,b)=>a.time-b.time)}
    else if(command.type==="SET_FACING"){const id=actor(p,command.actor),current=poseAt(p.tracks[id],time),wantLeft=command.target?poseAt(p.tracks[actor(p,command.target)],time).root.x<current.root.x:command.facing==="LEFT",q=isFacingLeft(current)===wantLeft?current:mirror(current);const character=p.characters.find(x=>x.id===id);if(character)character.flip=wantLeft;p.tracks[id].push({id:uid(),time,pose:q,easing:"hold",flipH:false});p.tracks[id].sort((a,b)=>a.time-b.time)}
    inserted.push({command:index+1,kind:command.type,time,ids:keyIds(before,p)});
  });const requested=sequence.durationMs!==undefined?sequence.durationMs/1000:sequence.duration;p.duration=Math.max(p.duration,requested??0);return{project:p,inserted}}

export class TimelineCommandError extends Error{constructor(message:string){super(message);this.name="TimelineCommandError"}}
export const addPose=(project:Project,input:Omit<Extract<TimelineCommand,{type:"POSE"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"POSE",...input}]}).project;
export const addAction=(project:Project,input:Omit<Extract<TimelineCommand,{type:"ACTION"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"ACTION",...input}]}).project;
export const addFightMove=(project:Project,input:Omit<Extract<TimelineCommand,{type:"FIGHT_MOVE"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"FIGHT_MOVE",...input}]}).project;
export const addReaction=(project:Project,input:Omit<Extract<TimelineCommand,{type:"REACTION"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"REACTION",...input}]}).project;
export const addCamera=(project:Project,input:Omit<Extract<TimelineCommand,{type:"CAMERA"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"CAMERA",...input}]}).project;
export const addEffect=(project:Project,input:Omit<Extract<TimelineCommand,{type:"EFFECT"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"EFFECT",...input}]}).project;
export const moveActor=(project:Project,input:Omit<Extract<TimelineCommand,{type:"MOVE_ACTOR"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"MOVE_ACTOR",...input}]}).project;
export const setFacing=(project:Project,input:Omit<Extract<TimelineCommand,{type:"SET_FACING"}>,"type">)=>applyTimelineSequence(project,{commands:[{type:"SET_FACING",...input}]}).project;

export function parseTimelineScript(script:string,project:Project):TimelineSequence{const commands:TimelineCommand[]=[],actors=[...project.characters].sort((a,b)=>b.name.length-a.name.length);for(const [lineIndex,raw] of script.split(/\r?\n/).entries()){const line=raw.trim();if(!line||line.startsWith("#"))continue;const match=line.match(/^@(\d+(?:\.\d+)?)(ms|s)\s+(.+)$/i);if(!match)throw new TimelineCommandError(`Line ${lineIndex+1}: expected @<time>ms or @<time>s`);const timing=match[2].toLowerCase()==="ms"?{timeMs:+match[1]}:{time:+match[1]},body=match[3];if(/^CAMERA\s+/i.test(body)){commands.push({type:"CAMERA",name:body.replace(/^CAMERA\s+/i,""),...timing});continue}if(/^EFFECT\s+/i.test(body)){commands.push({type:"EFFECT",name:body.replace(/^EFFECT\s+/i,""),...timing});continue}const owner=actors.find(a=>norm(body).startsWith(norm(a.name)+"_")||norm(body)===norm(a.name));if(!owner)throw new TimelineCommandError(`Line ${lineIndex+1}: unknown actor prefix`);const rest=body.slice(owner.name.length).trim(),kind=rest.match(/^(POSE|ACTION|FIGHT|REACTION|MOVE|FACING)\s+/i)?.[1]?.toUpperCase();if(!kind)throw new TimelineCommandError(`Line ${lineIndex+1}: unknown command`);const value=rest.replace(/^\w+\s+/i,"");if(kind==="POSE")commands.push({type:"POSE",actor:owner.id,name:value,...timing});else if(kind==="ACTION")commands.push({type:"ACTION",actor:owner.id,name:value,...timing});else if(kind==="REACTION")commands.push({type:"REACTION",actor:owner.id,name:value,...timing});else if(kind==="FACING")commands.push({type:"SET_FACING",actor:owner.id,facing:norm(value)==="left"?"LEFT":"RIGHT",...timing});else if(kind==="FIGHT"){const executionMatch=value.match(/\s+(ATTACKER_ONLY|PAIRED)$/i),withoutExecution=executionMatch?value.slice(0,executionMatch.index).trim():value,parts=withoutExecution.split(/\s*->\s*/);if(parts.length!==2)throw new TimelineCommandError(`Line ${lineIndex+1}: expected FIGHT <name> -> <actor> [ATTACKER_ONLY|PAIRED]`);commands.push({type:"FIGHT_MOVE",attacker:owner.id,target:parts[1],name:parts[0],execution:(executionMatch?.[1].toUpperCase() as "ATTACKER_ONLY"|"PAIRED")??"PAIRED",...timing})}else{const move=value.match(/^(?:TO\s+)?(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)$/i);if(!move)throw new TimelineCommandError(`Line ${lineIndex+1}: expected MOVE <x> <y>`);commands.push({type:"MOVE_ACTOR",actor:owner.id,x:+move[1],y:+move[2],...timing})}}return{commands}}
