export type V = { x: number; y: number };
export type ActorId = string;
export type EntityId = string;
export type JointName =
  | "root"
  | "torso"
  | "neck"
  | "head"
  | "leftShoulder"
  | "leftElbow"
  | "leftWrist"
  | "rightShoulder"
  | "rightElbow"
  | "rightWrist"
  | "leftHip"
  | "leftKnee"
  | "leftAnkle"
  | "leftToe"
  | "rightHip"
  | "rightKnee"
  | "rightAnkle"
  | "rightToe";
export type Pose = Record<JointName, V>;
export type BodyProfile = "standard" | "male" | "female" | "child" | "large" | "small";
export type HeadAccessory = "none" | "headband" | "hat" | "hood";
export type FaceAccessory = "none" | "mask" | "ninja-mask" | "glasses";
export type BodyAccessory = "none" | "scarf" | "cape";
export type CharacterEquipment = "none" | "sword" | "knife" | "staff";
export interface CharacterAppearance {
  primaryColor: string;
  accentColor: string;
  head: HeadAccessory;
  face: FaceAccessory;
  body: BodyAccessory;
}
export interface CharacterAsset {
  id: string;
  name: string;
  bodyProfile: BodyProfile;
  appearance: CharacterAppearance;
  equipment: CharacterEquipment;
  previewSettings: { action: "idle" };
  createdAt: string;
  updatedAt: string;
}
export type Ease =
  "linear" | "ease-in" | "ease-out" | "ease-in-out" | "snap" | "hold";
export interface Character {
  id: ActorId;
  name: string;
  type?: "stick_character";
  preset?: "standard" | "male" | "female" | "child" | "large" | "small";
  color: string;
  pose: Pose;
  flip: boolean;
  scale: number;
  rotation: number;
  visible: boolean;
  locked?: boolean;
  layer?: number;
  characterAssetId?: string;
  appearance?: CharacterAppearance;
  equipment?: CharacterEquipment;
}
export interface PoseKeyframe {
  id: string;
  time: number;
  pose: Pose;
  easing: Ease;
  rotation?: number;
  scaleX?: number;
  scaleY?: number;
  flipH?: boolean;
  flipV?: boolean;
  /** Ordinary editable keyframes generated by the deterministic Auto Motion authoring tool. */
  source?: "AUTO_MOTION" | "AUTO_MOTION_MODIFIED" | "MOTION_PATH" | "MOTION_PATH_MODIFIED";
  autoMotionGroupId?: string;
  autoMotionAnchorStartId?: string;
  autoMotionAnchorEndId?: string;
  motionPathId?: string;
  /** Reusable Action instance that authored this editable Timeline key. */
  actionId?: string;
  actionInstanceId?: string;
}
export interface MotionReviewIssue {
  id: string;
  actorId: ActorId;
  time: number;
  sourceTime?: number;
  joints: JointName[];
  reason: string;
  severity: "low" | "medium" | "high";
  status: "reconstructed" | "review" | "resolved";
}
export interface CharacterTransform {
  rotation: number;
  scaleX: number;
  scaleY: number;
  flipH: boolean;
  flipV: boolean;
}
export type PropType =
  | "chair"
  | "table"
  | "sofa"
  | "bed"
  | "bench"
  | "phone"
  | "cup"
  | "book"
  | "bag"
  | "umbrella"
  | "flower"
  | "gift"
  | "letter"
  | "sword"
  | "knife"
  | "staff"
  | "spear"
  | "gun"
  | "shield"
  | "flashlight"
  | "radio"
  | "ball"
  | "rectangle"
  | "circle"
  | "line"
  | "image";
export interface PropAttachment {
  actorId: ActorId;
  joint: JointName;
  offsetX: number;
  offsetY: number;
  rotation: number;
}
export interface PropTransform {
  x: number;
  y: number;
  rotation: number;
  scaleX: number;
  scaleY: number;
  flipH: boolean;
  opacity: number;
  attachment: PropAttachment | null;
}
export interface Prop {
  id: EntityId;
  name: string;
  type: PropType;
  color: string;
  visible: boolean;
  locked: boolean;
  layer: number;
  image?: string;
}
export interface PropKeyframe extends PropTransform {
  id: string;
  time: number;
  easing: Ease;
  source?: "MOTION_PATH" | "MOTION_PATH_MODIFIED";
  motionPathId?: string;
}
export type MotionPathType = "straight" | "polyline" | "bezier" | "free-draw";
export type MotionPathEasing = "linear" | "ease-in" | "ease-out" | "ease-in-out";
export type MotionPathDensity = "low" | "medium" | "high";
export type PathVisibilityMode = "selected" | "all" | "hidden";
export interface MotionPathPoint { id:string; x:number; y:number; in?:V; out?:V }
export interface MotionPath {
  id:string; name:string; targetId:string; targetType:"character"|"prop";
  pathType:MotionPathType; points:MotionPathPoint[];
  startTime:number; endTime:number; easing:MotionPathEasing;
  orientToPath:boolean; density:MotionPathDensity; visible:boolean;
  createdAt:string; updatedAt:string;
}
export interface CameraState {
  x: number;
  y: number;
  zoom: number;
  rotation: number;
}
export interface CameraKeyframe extends CameraState {
  id: string;
  time: number;
  easing: Ease;
}
export interface SpeedKeyframe {
  id: string;
  time: number;
  speed: number;
  easing?: Ease;
}
export interface CinematicRegion { id:string;preset:string;start:number;impact:number;end:number }
export interface MasterClip {id:string;name:string;source:Project;in:number;out:number;transition:"cut"|"fade"}
export interface MasterSequence {id:string;name:string;clips:MasterClip[];format?:Project["format"]}
export type EffectType =
  | "flash"
  | "shockwave"
  | "lines"
  | "dust"
  | "shake"
  | "tether"
  | "frozen"
  | "stunned"
  | "motionTrail" | "afterimage" | "sparks" | "hitParticles" | "clash" | "blood" | "aura";
export type BloodLevel = "OFF" | "LOW" | "MEDIUM" | "HIGH";
export interface EffectAnimationKey {
  id: string;
  /** Absolute project time. */
  time: number;
  scale: number;
  arc: number;
  spread: number;
  range: number;
  scatterRadius: number;
  density: number;
  opacity: number;
}
export interface Effect {
  id: string;
  time: number;
  duration: number;
  type: EffectType;
  x: number;
  y: number;
  strength: number;
  style?: "line" | "rope" | "chain" | "energy";
  sourceFighter?: ActorId;
  targetFighter?: ActorId;
  layer?: "behind" | "between" | "front";
  preset?: string;
  trackedJoint?: JointName;
  /** Prop used by a real weapon trail. The renderer samples its blade base/tip. */
  trackedProp?: EntityId;
  directionX?: number;
  directionY?: number;
  trackedPoint?: "weapon" | "hand" | "fist" | "foot" | "body" | "projectile";
  width?: number;
  sampleCount?: number;
  minimumVelocity?: number;
  maximumTrailAge?: number;
  opacity?: number;
  glow?: number;
  color?: string;
  secondaryColor?: string;
  autoTrail?: boolean;
  bloodLevel?: BloodLevel;
  particleSpread?: number;
  particleCount?: number;
  particleSpeed?: number;
  userScale?: number;
  arcDegrees?: number;
  scatterRadius?: number;
  auraStyle?: "flame" | "spike" | "palm" | "vortex" | "ring" | "dragon" | "speed" | "wings" | "force" | "shards" | "lightning";
  animationKeys?: EffectAnimationKey[];
}
export interface CombatFxSettings {
  intensity: "OFF" | "LOW" | "MEDIUM" | "HIGH" | "ARCADE";
  hitParticles: boolean;
  autoWeaponTrail: boolean;
  blood: BloodLevel;
  bloodSpread?: number;
  bloodAmount?: number;
  bloodDistance?: number;
}
export interface FightInstance {
  id: string;
  seed: number;
  settings: Record<string, unknown>;
  packageId?: string;
  fighterAssignments: { attacker: ActorId; target: ActorId; winner?: ActorId };
  startTime: number;
  endTime: number;
  generatedMoveIds: string[];
}
export type CombatType = "UNARMED" | "SWORD" | "MIXED";
export type WeaponHand = "right" | "left";
export interface SpecialEvent {
  time: number;
  type: string;
  fighter?: "attacker" | "defender";
  pose?: string;
  action?: string;
  duration?: number;
  scale?: number;
  x?: number;
  y?: number;
  rotation?: number;
  strength?: number;
  target?: string;
  style?: "line" | "rope" | "chain" | "energy";
  preset?: string;
  speed?: number;
  easing?: Ease;
}
export interface SpecialMove {
  id: string;
  name: string;
  category: string;
  duration: number;
  description: string;
  events: SpecialEvent[];
  participants?: 1 | 2;
}
export interface ActionKeyframe {
  actorIndex?: number;
  time: number;
  pose: string;
  easing: Ease;
  dx?: number;
  dy?: number;
  rootRotation?: number;
  /** Exact reusable pose captured from a project timeline. */
  inlinePose?: Pose;
}
export interface Action {
  id?: string;
  name: string;
  description?: string;
  categories?: string[];
  subcategory?: string;
  tags?: string[];
  participants?: ("actor" | "prop")[];
  style?: string;
  beats?: number;
  bars?: number;
  intensity?: "Low" | "Medium" | "High" | "Acrobatic";
  loopable?: boolean;
  supportedOrientations?: ("FRONT"|"THREE_QUARTER_LEFT"|"SIDE_LEFT"|"THREE_QUARTER_RIGHT"|"SIDE_RIGHT")[];
  interactionEvents?: {time:number;type:"GRAB"|"RELEASE"|"TRANSFER"|"CATCH";actorIndex?:number;toActorIndex?:number;joint?:JointName}[];
  entryPose?: string;
  mainPose?: string;
  exitPose?: string;
  duration: number;
  keyframes: ActionKeyframe[];
  rootMotion?: "relative" | "in-place";
  facing?: "original" | "left" | "right";
  createdAt?: string;
  updatedAt?: string;
  lastUsedAt?: string;
}
export interface ActionCategoryMeta {
  id: string;
  name: string;
  sortOrder: number;
  isSystem: boolean;
  createdAt: string;
  updatedAt: string;
}
export interface Project {
  version: 1;
  name: string;
  duration: number;
  fps: number;
  format: { label: string; width: number; height: number };
  characters: Character[];
  tracks: Record<ActorId, PoseKeyframe[]>;
  props?: Prop[];
  propTracks?: Record<EntityId, PropKeyframe[]>;
  camera: CameraKeyframe[];
  speed: SpeedKeyframe[];
  cinematics?: CinematicRegion[];
  master?: MasterSequence;
  effects: Effect[];
  background: { top: string; bottom: string; grid: boolean; image?: string };
  savedPoses: Record<string, Pose>;
  trail: 0 | 1 | 2 | 3;
  dance?: { bpm: number; beatGrid: boolean; snapToBeat: boolean };
  motionReviews?: MotionReviewIssue[];
  director?: import("./autoDirector").AutoDirectorState;
  combatFx?: CombatFxSettings;
  fights?: FightInstance[];
  /** User-authored reusable actions stored with the project. */
  customActions?: Action[];
  /** User-managed categories in addition to the built-in category set. */
  actionCategories?: string[];
  /** Metadata for user categories; string names above remain for backwards compatibility. */
  actionCategoryMeta?: ActionCategoryMeta[];
  /** Editor guides. Baked playback does not depend on these paths. */
  motionPaths?: MotionPath[];
  pathVisibility?: PathVisibilityMode;
}
